-- HOGAR CON SUS DETALLES

SELECT H.DIRECCION, H.LOCALIDAD, H.PROVINCIA, D.NOMBRE AS DETALLE
FROM HOGAR H
INNER JOIN HOGAR_DATO_VIVIENDA HD ON(H.ID_HOGAR=HD.ID_HOGAR)
INNER JOIN DATO_VIVIENDA D ON(HD.ID_DATO_VIVIENDA=D.ID_DETALLE);

-- DUEÑOS DE HOGARES ASEGURADOS

SELECT P.ID_POLIZA, P.NOMBRE, P.APELLIDO, H.DIRECCION, H.LOCALIDAD
FROM PERSONA P
INNER JOIN TOMADOR T ON (P.ID_PERSONA=T.ID_PERSONA)
INNER JOIN POLIZA P ON (T.ID_POLIZA=P.ID_POLIZA)
INNER JOIN HOGAR H ON (H.ID_HOGAR=P.ID_HOGAR);

-- Siniestros cubiertos pos su poliza (en este caso, para el siniestro con id = 3)

SELECT * 
FROM POLIZA_COBERTURAS pc INNER JOIN COBERTURA_RIESGO cr ON ( pc.ID_COBERTURA = cr.ID_COBERTURA ) 
                          INNER JOIN RIESGO r ON (cr.ID_RIESGO = r.ID_RIESGO) 
                          INNER JOIN SINIESTRO s ON ( r.ID_RIESGO = s.ID_RIESGO ) 
WHERE  s.ID_POLIZA = pc.ID_POLIZA  AND s.ID_SINIESTRO = 3;

-- Polizas con sus coberturas y los riegos que estos abarcan

SELECT * 
FROM POLIZA_COBERTURAS pc LEFT JOIN COBERTURA_RIESGO cr ON ( pc.ID_COBERTURA = cr.ID_COBERTURA ) 
                          LEFT JOIN RIESGO r ON (cr.ID_RIESGO = r.ID_RIESGO) 
ORDER BY pc.ID_POLIZA, pc.ID_COBERTURA, cr.ID_RIESGO ;

-- Hogares con sus datos de vivienda

SELECT * 
FROM HOGAR h INNER JOIN HOGAR_DATO_VIVIENDA hdv ON (h.ID_HOGAR = hdv.ID_HOGAR) 
             INNER JOIN DATO_VIVIENDA dv ON ( hdv.ID_DATO_VIVIENDA = dv.ID_DETALLE );

-- Polizas vendidas por los productoes
SELECT * 
FROM PRODUCTOR p INNER JOIN PRODUCTOR_POLIZA pp ON ( p.ID_PRODUCTOR = pp.ID_PRODUCTOR ) 
                 INNER JOIN POLIZA pol ON (pp.ID_POLIZA = pol.ID_POLIZA);
				 
-- COBERTURAS ADHERIDAS A POLIZA
SELECT *
FROM ANEXO_COBERTURA AC
JOIN ANEXO A
  ON (AC.ID_ANEXO = A.ID_ANEXO)
JOIN COBERTURA C
  ON (AC.ID_COBERTURA = C.ID_COBERTURA);
  
-- POLIZAS VENCIDAS O QUE VENCEN EN EL DIA DE LA FECHA
SELECT *
FROM POLIZA
WHERE FECHA_VENCIMIENTO <= SYSDATE

-- CANTIDAD DE POLIZAS VENDIDAS POR CADA PRODUCTOR

SELECT pro.ID_PRODUCTOR, pro.RAZON_SOCIAL, NVL (count( pp.ID_POLIZA ), 0 ) as "Polizas Vendidas"
FROM PRODUCTOR pro LEFT JOIN PRODUCTOR_POLIZA pp ON ( pro.ID_PRODUCTOR = pp.ID_PRODUCTOR )
GROUP BY pro.ID_PRODUCTOR, pro.RAZON_SOCIAL
ORDER BY pro.RAZON_SOCIAL;

-- PLANES DE CADA POLIZA Y SUS DETALLES

SELECT POL.ID_POLIZA, POL.TIPO_PLAN, POL_PLA.ID_PLAN, PLA.NOMBRE, PLA.DESCRIPCION, PLA_COB.ID_COBERTURA, COB.DESCRIPCION
FROM POLIZA POL
INNER JOIN POLIZA_PLAN POL_PLA ON (POL.ID_POLIZA = POL_PLA.ID_POLIZA)
INNER JOIN PLANES PLA ON (PLA.ID_PLAN = POL_PLA.ID_PLAN)
INNER JOIN PLAN_COBERTURA PLA_COB ON (PLA_COB.ID_PLAN = PLA.ID_PLAN)
INNER JOIN COBERTURA COB ON (COB.ID_COBERTURA = PLA_COB.ID_COBERTURA)
ORDER BY POL.ID_POLIZA;

--CANTIDAD DE POLIZAS POR PERSONAS

SELECT P.NOMBRE, P.APELLIDO, COUNT(T.ID_POLIZA) AS "CANTIDAD DE POLIZAS"
FROM PERSONA P
INNER JOIN TOMADOR T ON (P.ID_PERSONA=T.ID_PERSONA)
INNER JOIN POLIZA POL ON (T.ID_POLIZA=POL.ID_POLIZA)
GROUP BY P.APELLIDO, P.NOMBRE
ORDER BY 3 DESC

--PERSONAS QUE NO TIENEN POLIZAS


SELECT P.NOMBRE, P.APELLIDO, P.ID_PERSONA
FROM PERSONA P
WHERE P.ID_PERSONA NOT IN (SELECT TOMADOR.ID_PERSONA
                            FROM TOMADOR);


                            
--LAS POLIZAS QUE TIENEN CADA TOMADOR--

select P.APELLIDO,P.NOMBRE,LISTAGG( T.ID_POLIZA,'-') WITHIN GROUP (ORDER BY T.ID_POLIZA ) POLIZAS
from persona P
INNER JOIN TOMADOR T ON T.ID_PERSONA=P.ID_PERSONA
INNER JOIN PERSONA P ON T.ID_PERSONA=P.ID_PERSONA
GROUP BY(P.NOMBRE,P.APELLIDO);

-- Suma de impuestos por poliza

SELECT p.ID_POLIZA, NVL(SUM(i.PORCENTAJE), 0) as porcentajes
FROM POLIZA p left JOIN POLIZA_IMPUESTO pi ON (p.ID_POLIZA = pi.ID_POLIZA) 
              left JOIN IMPUESTO i ON (pi.ID_IMPUESTO = i.ID_IMPUESTO )
GROUP BY p.ID_POLIZA
ORDER BY 2 DESC

--PERSONAS QUE SON TESTIGOS DE SINIESTROS
SELECT *
FROM PERSONA P
INNER JOIN SINIESTRO_TESTIGO ST ON (P.ID_PERSONA=ST.ID_PERSONA)
INNER JOIN SINIESTRO S ON (S.ID_SINIESTRO=ST.ID_SINIESTRO)
