-- Generated by Oracle SQL Developer Data Modeler 4.0.3.853
--   at:        2015-08-24 13:54:20 ART
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE anexo
  (
    id_anexo    INTEGER NOT NULL ,
    descripcion VARCHAR2 (100) NOT NULL ,
    operacion   VARCHAR2 (50) NOT NULL
  ) ;
ALTER TABLE anexo ADD CONSTRAINT anexo_PK PRIMARY KEY ( id_anexo ) ;

CREATE TABLE anexo_cobertura
  (
    id_anexo_cobertura INTEGER NOT NULL ,
    id_anexo           INTEGER NOT NULL ,
    id_cobertura       INTEGER NOT NULL
  ) ;
ALTER TABLE anexo_cobertura ADD CONSTRAINT anexo_cobertura_PK PRIMARY KEY ( id_anexo_cobertura ) ;

CREATE TABLE cobertura
  (
    id_cobertura INTEGER NOT NULL ,
    descripcion  VARCHAR2 (300) NOT NULL ,
	precio FLOAT NOT NULL
  ) ;
ALTER TABLE cobertura ADD CONSTRAINT cobertura_PK PRIMARY KEY ( id_cobertura ) ;

CREATE TABLE cobertura_riesgo
  (
    id_riesgo    INTEGER NOT NULL ,
    id_cobertura INTEGER NOT NULL
  ) ;
ALTER TABLE cobertura_riesgo ADD CONSTRAINT cobertura_riesgo_PK PRIMARY KEY ( id_riesgo, id_cobertura ) ;

CREATE TABLE comisiones
  (
    id_comision  INTEGER NOT NULL ,
    fecha_inicio DATE NOT NULL ,
    fecha_fin    DATE ,
    porcentaje FLOAT NOT NULL ,
    id_productor_poliza INTEGER NOT NULL
  ) ;
ALTER TABLE comisiones ADD CONSTRAINT Comisiones_PK PRIMARY KEY ( id_comision ) ;

CREATE TABLE dato_vivienda
  (
    id_detalle  INTEGER NOT NULL ,
    nombre      VARCHAR2 (50) NOT NULL ,
    descripcion VARCHAR2 (200)
  ) ;
ALTER TABLE dato_vivienda ADD CONSTRAINT detalles_hogar_PK PRIMARY KEY ( id_detalle ) ;

CREATE TABLE detalle_cobertura
  (
    id_objeto   INTEGER NOT NULL ,
    descripcion VARCHAR2 (100) NOT NULL ,
    cotizacion FLOAT NOT NULL ,
    id_cobertura INTEGER NOT NULL ,
    id_poliza    INTEGER NOT NULL
  ) ;
ALTER TABLE detalle_cobertura ADD CONSTRAINT objetos_PK PRIMARY KEY ( id_objeto ) ;

CREATE TABLE hogar
  (
    id_hogar         INTEGER NOT NULL ,
    direccion        VARCHAR2 (100) NOT NULL ,
    dpto             VARCHAR2 (10) ,
    piso             INTEGER ,
    localidad        VARCHAR2 (50) NOT NULL ,
    codigo_postal    INTEGER NOT NULL ,
    provincia        VARCHAR2 (50) NOT NULL ,
    metros_cubiertos INTEGER NOT NULL ,
    id_zona          INTEGER NOT NULL
  ) ;
ALTER TABLE hogar ADD CONSTRAINT Hogar_PK PRIMARY KEY ( id_hogar ) ;

CREATE TABLE hogar_dato_vivienda
  (
    id_hogar         INTEGER NOT NULL ,
    id_dato_vivienda INTEGER NOT NULL
  ) ;
ALTER TABLE hogar_dato_vivienda ADD CONSTRAINT hogar_dato_vivienda_PK PRIMARY KEY ( id_hogar, id_dato_vivienda ) ;

CREATE TABLE impuesto
  (
    id_impuesto    INTEGER NOT NULL ,
    DESCRIPCION    VARCHAR2 (20 CHAR) NOT NULL ,
    suma           INTEGER NOT NULL
  ) ;
ALTER TABLE impuesto ADD CONSTRAINT Impuesto_PK PRIMARY KEY ( id_impuesto ) ;

CREATE TABLE persona
  (
    id_persona     		INTEGER NOT NULL ,
    nombre         		VARCHAR2 (50) NOT NULL ,
    apellido       		VARCHAR2 (50) NOT NULL ,
    tipo_documento 		VARCHAR2 (30) NOT NULL ,
    nro_documento  		INTEGER NOT NULL,
	fecha_nacimiento 	DATE NOT NULL ,
	telefono_celular  	VARCHAR2 (25) ,
    telefono_fijo     	VARCHAR2 (25) ,
    direccion        	VARCHAR2 (100) NOT NULL ,
    dpto             	VARCHAR2 (10) ,
    piso             	INTEGER ,
    localidad        	VARCHAR2 (50) NOT NULL ,
    codigo_postal    	INTEGER NOT NULL ,
    provincia        	VARCHAR2 (50) NOT NULL
  ) ;
  
  
ALTER TABLE persona ADD CONSTRAINT Persona_PK PRIMARY KEY ( id_persona ) ;

CREATE TABLE plan
  (
    id_plan     INTEGER NOT NULL ,
    nombre      VARCHAR2 (30) NOT NULL ,
    descripcion VARCHAR2 (300)
  ) ;
ALTER TABLE plan ADD CONSTRAINT Plan_PK PRIMARY KEY ( id_plan ) ;

CREATE TABLE plan_cobertura
  (
    id_plan_cobertura INTEGER NOT NULL ,
    id_plan           INTEGER NOT NULL ,
    id_cobertura      INTEGER NOT NULL
  ) ;
ALTER TABLE plan_cobertura ADD CONSTRAINT plan_cobertura_PK PRIMARY KEY ( id_plan_cobertura ) ;

CREATE TABLE poliza
  (
    id_poliza         INTEGER NOT NULL ,
    tipo              VARCHAR2 (30) NOT NULL ,
    premio            INTEGER NOT NULL ,
    fecha_emision     DATE NOT NULL ,
    fecha_vencimiento DATE NOT NULL ,
    tipo_plan         VARCHAR2 (50) NOT NULL ,
    id_hogar          INTEGER NOT NULL ,
	vigente			  INTEGER NOT NULL --1: TRUE, 0: FALSE  (falso boolean)
  ) ;
ALTER TABLE poliza ADD CONSTRAINT Poliza_PK PRIMARY KEY ( id_poliza ) ;

CREATE TABLE poliza_anexo
  (
    id_poliza         INTEGER NOT NULL ,
    id_anexo          INTEGER NOT NULL ,
    fecha_emision     DATE NOT NULL ,
    fecha_vencimiento DATE NOT NULL
  ) ;
ALTER TABLE poliza_anexo ADD CONSTRAINT poliza_anexo_PK PRIMARY KEY ( id_poliza, id_anexo ) ;

CREATE TABLE poliza_impuesto
  (
    id_poliza   INTEGER NOT NULL ,
    id_impuesto INTEGER NOT NULL
  ) ;
ALTER TABLE poliza_impuesto ADD CONSTRAINT poliza_impuesto_PK PRIMARY KEY ( id_poliza, id_impuesto ) ;

CREATE TABLE poliza_plan
  (
    fecha_emision     DATE NOT NULL ,
    fecha_vencimiento DATE ,
    id_plan           INTEGER NOT NULL ,
    id_poliza         INTEGER NOT NULL
  ) ;
ALTER TABLE poliza_plan ADD CONSTRAINT poliza_plan_PK PRIMARY KEY ( id_plan, id_poliza ) ;

CREATE TABLE productor
  (
    id_productor INTEGER NOT NULL ,
    descripcion  VARCHAR2 (300) ,
    razon_social VARCHAR2 (100) NOT NULL ,
    cuit_cuil  INTEGER NOT NULL
  ) ;
ALTER TABLE productor ADD CONSTRAINT productor_PK PRIMARY KEY ( id_productor ) ;

CREATE TABLE productor_poliza
  (
    id_productor_poliza INTEGER NOT NULL ,
    id_productor        INTEGER NOT NULL ,
    id_poliza           INTEGER NOT NULL
  ) ;
ALTER TABLE productor_poliza ADD CONSTRAINT productor_poliza_PK PRIMARY KEY ( id_productor_poliza ) ;

CREATE TABLE riesgo
  (
    id_riesgo   INTEGER NOT NULL ,
    descripcion VARCHAR2 (300) NOT NULL
  ) ;
ALTER TABLE riesgo ADD CONSTRAINT riesgo_PK PRIMARY KEY ( id_riesgo ) ;

CREATE TABLE siniestro
  (
    id_siniestro INTEGER NOT NULL ,
    fecha_hora   TIMESTAMP NOT NULL ,
    descripcion  VARCHAR2 (300) NOT NULL ,
    id_riesgo    INTEGER NOT NULL ,
    id_poliza    INTEGER NOT NULL
  ) ;
ALTER TABLE siniestro ADD CONSTRAINT siniestro_PK PRIMARY KEY ( id_siniestro ) ;

CREATE TABLE siniestro_testigo
  (
    id_siniestro INTEGER NOT NULL ,
    id_persona   INTEGER NOT NULL
  ) ;
ALTER TABLE siniestro_testigo ADD CONSTRAINT siniestro_testigo_PK PRIMARY KEY ( id_siniestro, id_persona ) ;

CREATE TABLE tomador
  (
    id_tomador INTEGER NOT NULL ,
    id_persona INTEGER NOT NULL ,
    id_poliza  INTEGER NOT NULL ,
  ) ;
ALTER TABLE tomador ADD CONSTRAINT Tomador_PK PRIMARY KEY ( id_tomador ) ;

CREATE TABLE zona
  (
    id_zona   INTEGER NOT NULL ,
    nombre    VARCHAR2 (100) NOT NULL ,
    localidad VARCHAR2 (50) NOT NULL
  ) ;
ALTER TABLE zona ADD CONSTRAINT Zona_PK PRIMARY KEY ( id_zona ) ;

ALTER TABLE comisiones ADD CONSTRAINT Comisiones_productor_poliza_FK FOREIGN KEY ( id_productor_poliza ) REFERENCES productor_poliza ( id_productor_poliza ) ;

ALTER TABLE hogar_dato_vivienda ADD CONSTRAINT Hogar_FK FOREIGN KEY ( id_hogar ) REFERENCES hogar ( id_hogar ) ;

ALTER TABLE hogar ADD CONSTRAINT Hogar_Zona_FK FOREIGN KEY ( id_zona ) REFERENCES zona ( id_zona ) ;

ALTER TABLE plan_cobertura ADD CONSTRAINT Plan_FK FOREIGN KEY ( id_plan ) REFERENCES plan ( id_plan ) ;

ALTER TABLE productor_poliza ADD CONSTRAINT Poliza_FK FOREIGN KEY ( id_poliza ) REFERENCES poliza ( id_poliza ) ;

ALTER TABLE tomador ADD CONSTRAINT Tomador_Persona_FK FOREIGN KEY ( id_persona ) REFERENCES persona ( id_persona ) ;

ALTER TABLE tomador ADD CONSTRAINT Tomador_Poliza_FK FOREIGN KEY ( id_poliza ) REFERENCES poliza ( id_poliza ) ;

ALTER TABLE anexo_cobertura ADD CONSTRAINT anexo_cobertura_anexo_FK FOREIGN KEY ( id_anexo ) REFERENCES anexo ( id_anexo ) ;

ALTER TABLE anexo_cobertura ADD CONSTRAINT anexo_cobertura_cobertura_FK FOREIGN KEY ( id_cobertura ) REFERENCES cobertura ( id_cobertura ) ;

ALTER TABLE plan_cobertura ADD CONSTRAINT cobertura_FK FOREIGN KEY ( id_cobertura ) REFERENCES cobertura ( id_cobertura ) ;

ALTER TABLE cobertura_riesgo ADD CONSTRAINT cobertura_riesgo_cobertura_FK FOREIGN KEY ( id_cobertura ) REFERENCES cobertura ( id_cobertura ) ;

ALTER TABLE cobertura_riesgo ADD CONSTRAINT cobertura_riesgo_riesgo_FK FOREIGN KEY ( id_riesgo ) REFERENCES riesgo ( id_riesgo ) ;

ALTER TABLE hogar_dato_vivienda ADD CONSTRAINT dato_vivienda_FK FOREIGN KEY ( id_dato_vivienda ) REFERENCES dato_vivienda ( id_detalle ) ;

ALTER TABLE detalle_cobertura ADD CONSTRAINT detalle_cobertura_FK FOREIGN KEY ( id_cobertura ) REFERENCES cobertura ( id_cobertura ) ;

ALTER TABLE detalle_cobertura ADD CONSTRAINT objetos_Poliza_FK FOREIGN KEY ( id_poliza ) REFERENCES poliza ( id_poliza ) ;

ALTER TABLE poliza_anexo ADD CONSTRAINT poliza_anexo_Poliza_FK FOREIGN KEY ( id_poliza ) REFERENCES poliza ( id_poliza ) ;

ALTER TABLE poliza_anexo ADD CONSTRAINT poliza_anexo_anexo_FK FOREIGN KEY ( id_anexo ) REFERENCES anexo ( id_anexo ) ;

ALTER TABLE poliza ADD CONSTRAINT poliza_hogar_FK FOREIGN KEY ( id_hogar ) REFERENCES hogar ( id_hogar ) ;

ALTER TABLE poliza_impuesto ADD CONSTRAINT poliza_impuesto_Impuesto_FK FOREIGN KEY ( id_impuesto ) REFERENCES impuesto ( id_impuesto ) ;

ALTER TABLE poliza_impuesto ADD CONSTRAINT poliza_impuesto_poliza_FK FOREIGN KEY ( id_poliza ) REFERENCES poliza ( id_poliza ) ;

ALTER TABLE poliza_plan ADD CONSTRAINT poliza_plan_Plan_FK FOREIGN KEY ( id_plan ) REFERENCES plan ( id_plan ) ;

ALTER TABLE poliza_plan ADD CONSTRAINT poliza_plan_Poliza_FK FOREIGN KEY ( id_poliza ) REFERENCES poliza ( id_poliza ) ;

ALTER TABLE productor_poliza ADD CONSTRAINT productor_FK FOREIGN KEY ( id_productor ) REFERENCES productor ( id_productor ) ;

ALTER TABLE siniestro ADD CONSTRAINT siniestro_Poliza_FK FOREIGN KEY ( id_poliza ) REFERENCES poliza ( id_poliza ) ;

ALTER TABLE siniestro ADD CONSTRAINT siniestro_riesgo_FK FOREIGN KEY ( id_riesgo ) REFERENCES riesgo ( id_riesgo ) ;

ALTER TABLE siniestro_testigo ADD CONSTRAINT siniestro_testigo_persona_FK FOREIGN KEY ( id_persona ) REFERENCES persona ( id_persona ) ;

ALTER TABLE siniestro_testigo ADD CONSTRAINT siniestro_testigo_siniestro_FK FOREIGN KEY ( id_siniestro ) REFERENCES siniestro ( id_siniestro ) ;


ALTER TABLE TOMADOR ADD CONSTRAINT unique_tomador_id_poliza UNIQUE (ID_POLIZA);

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            23
-- CREATE INDEX                             0
-- ALTER TABLE                             48
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
